name: shop-api
channels:
        - conda-forge
dependencies:
        - backoff
        - flask-restx
        - flask
        - flask_cors
        - gevent
        - gunicorn
        - marshmallow
        - pip
        - requests
        - pytest
        - python=3.9
        - werkzeug=2.1.2
        - langchain
        - openai
        - python-dotenv
        - pip:
                - celery
                - config-probe
                - pytest-cov
                - tox-conda
                - ShopifyAPI
                - redis
                - tiktoken
                - git+https://github.com/korbit-ai/python-config-probe.git
