import enum


class DocType(enum.Enum):
    POLICY = "POLICY"
    PRODUCT = "PRODUCT"
    PRODUCT_DETAIL = "PRODUCT_DETAIL"
    PRODUCT_BODY = "PRODUCT_BODY"
    PRODUCT_VARIANT = "PRODUCT_VARIANT"
    CATEGORY = "CATEGORY"
